### ISSUE TITLE
Create Blog page

### ISSUE THREAD

**Issue by morganjess** [BellJohn/DC2060#25]
Update on development progress, team's journey so far

**Comment by morganjess** [comment]
@BellJohn I have created a page for the blog - not really sorted it out yet but I think you have it set up so only logged in users can see certain pages. Do you think the About page and the Blog page we can allow all users to see?

**Comment by morganjess** [comment]
change accessibility - spring xml

**Comment by morganjess** [comment]
Be able to upload files to the blog page - load files

**Comment by BellJohn** [comment]
![BlogPostIdea](https://user-images.githubusercontent.com/10315664/79258129-993d4880-7e82-11ea-8278-197d7a903a53.png)

This was my rough idea for the process. For step 5, you could either have the controller create one master String containing the whole stylized html to insert into the jsp or pass the collection of BlogPost objects up to the jsp and have some tags there which handle the loop and page structure creation.

The tags one is easier to maintain and would be the better option.
See this: https://stackoverflow.com/questions/15839335/using-for-loop-inside-of-a-jsp 
We already bring in the taglibrary in other pages so would be fairly easy to make use of.

Check out http://www.devsphere.com/mapping/docs/guide/dynamic.html 
In the section titled 8.2. Dynamic HTML Form it shows you how to generate a table dynamically with _i_ number of rows in it.

**Comment by BellJohn** [comment]
In fact, just the first link is sufficient. The second is a bit naff. 
That shows you the use of the tags for looping over the content of a collection and forming html from it.
