### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by BellJohn** [BellJohn/DC2060#7]
Need a user's profile page

**Comment by morganjess** [comment]
Would be good to add pictures for users, would this need to be amended in the db? Store it as a string?

**Comment by BellJohn** [comment]
Sounds good. Store the images on the file system and store their path in the db.
One thing we need to be careful of is retrieving the files every time we use a User object in the code. Proxy design would be good for this.

**Comment by morganjess** [comment]
Hi John, I will have a go at doing an update user details type page and see if I do the code to update database. Do we want to have a new table for user details which is linked to a username or do we want to expand on the user database, not sure what is best practice? 
These are the steps I am thinking I need to do so let me know if I am missing anything:
1. Create jsp page - form for the inputs
2. Create UpdateProfileController, I will look at your SignupController for the basic format
3. Create new database/change database
4. Make sure they are all interacting with each other as they should be

**Comment by morganjess** [comment]
User object store profile pic name or another table for pictures mapped to ids
New table pic id, userid, filename
Profile page loads up the picture.

**Comment by morganjess** [comment]
- [ ] get profile pictures upload set up 

- [ ] change the positioning of the profile and update profile
